### ISSUE TITLE
configure file does not exist

### ISSUE THREAD

**Issue by churchilldu** [ehForwarderBot/efb-voice_recog-middleware#3]
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 163, in init
    coordinator.add_middleware(cls(instance_id=instance_id))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/efb_voice_recog_middleware/__init__.py", line 42, in __init__
    self.config: Dict[str: Any] = self.load_config()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/efb_voice_recog_middleware/__init__.py", line 66, in load_config
    raise FileNotFoundError('The configure file does not exist!')
FileNotFoundError: The configure file does not exist!
```
但是配置文件确实存在  `$HOME/.ehforwarderbot/profiles/default/catbaron.voice_recog/config.yaml` 路径下。

**Comment by churchilldu** [comment]
解决方法：
例如有 wechat 实例，配置文件应该在
`$HOME/.ehforwarderbot/profiles/wechat/catbaron.voice_recog/config.yaml`
